In [528]:
import pandas as pd

In [529]:
df = pd.read_csv("./data/survey lung cancer.csv")
df

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

The effectiveness of cancer prediction system helps the people to know their cancer risk with low cost and it also helps the people to take the appropriate decision based on their cancer risk status. The data is collected from the website online lung cancer prediction system .
Total no. of attributes:16
No .of instances:284
Attribute information:

1. Gender: M(male), F(female)
2. Age: Age of the patient
3. Smoking: YES=2 , NO=1.
4. Yellow fingers: YES=2 , NO=1.
5. Anxiety: YES=2 , NO=1.
6. Peer_pressure: YES=2 , NO=1.
7. Chronic Disease: YES=2 , NO=1.
8. Fatigue: YES=2 , NO=1.
9. Allergy: YES=2 , NO=1.
10. Wheezing: YES=2 , NO=1.
11. Alcohol: YES=2 , NO=1.
12. Coughing: YES=2 , NO=1.
13. Shortness of Breath: YES=2 , NO=1.
14. Swallowing Difficulty: YES=2 , NO=1.
15. Chest pain: YES=2 , NO=1.
16. Lung Cancer: YES , NO.

In [530]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 309 non-null    str
 1   AGE                    309 non-null    int64
 2   SMOKING                309 non-null    int64
 3   YELLOW_FINGERS         309 non-null    int64
 4   ANXIETY                309 non-null    int64
 5   PEER_PRESSURE          309 non-null    int64
 6   CHRONIC DISEASE        309 non-null    int64
 7   FATIGUE                309 non-null    int64
 8   ALLERGY                309 non-null    int64
 9   WHEEZING               309 non-null    int64
 10  ALCOHOL CONSUMING      309 non-null    int64
 11  COUGHING               309 non-null    int64
 12  SHORTNESS OF BREATH    309 non-null    int64
 13  SWALLOWING DIFFICULTY  309 non-null    int64
 14  CHEST PAIN             309 non-null    int64
 15  LUNG_CANCER            309 non-null    str
dtypes: int64(14), str(2)
memory usage: 38.8 KB

In [531]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.strip()
df.rename(columns={"chronic disease": "chronic_disease", "alcohol consuming": "alcohol_consumption", "shortness of breath": "shortness_of_breath", "swallowing difficulty": "swallowing_difficulty", "chest pain": "chest_pain", "lung_cancer": "target"}, inplace=True)
df

,gender,age,smoking,yellow_fingers,anxiety,peer_pressure,chronic_disease,fatigue,allergy,wheezing,alcohol_consumption,coughing,shortness_of_breath,swallowing_difficulty,chest_pain,target
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [532]:
df.replace({"gender": {"M": 0, "F": 1}, "target": {"NO": 0, "YES": 1}}, inplace=True)

,gender,age,smoking,yellow_fingers,anxiety,peer_pressure,chronic_disease,fatigue,allergy,wheezing,alcohol_consumption,coughing,shortness_of_breath,swallowing_difficulty,chest_pain,target
0,0,69,1,2,2,1,1,2,1,2,2,2,2,2,2,1
1,0,74,2,1,1,1,2,2,2,1,1,1,2,2,2,1
2,1,59,1,1,1,2,1,2,1,2,1,2,2,1,2,0
3,0,63,2,2,2,1,1,1,1,1,2,1,1,2,2,0
4,1,63,1,2,1,1,1,1,1,2,1,2,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,1,56,1,1,1,2,2,2,1,1,2,2,2,2,1,1
305,0,70,2,1,1,1,1,2,2,2,2,2,2,1,2,1
306,0,58,2,1,1,1,1,1,2,2,2,2,1,1,2,1
307,0,67,2,1,2,1,1,2,2,1,2,2,2,1,2,1
308,0,62,1,1,1,2,1,2,2,2,2,1,1,2,1,1

In [533]:
change_2_1_yes_no_to_1_0 = {1: 0, 2: 1}
df.replace({
    "smoking": change_2_1_yes_no_to_1_0,
    "yellow_fingers": change_2_1_yes_no_to_1_0,
    "anxiety": change_2_1_yes_no_to_1_0,
    "peer_pressure": change_2_1_yes_no_to_1_0,
    "chronic_disease": change_2_1_yes_no_to_1_0,
    "fatigue": change_2_1_yes_no_to_1_0,
    "allergy": change_2_1_yes_no_to_1_0,
    "wheezing": change_2_1_yes_no_to_1_0,
    "alcohol_consumption": change_2_1_yes_no_to_1_0,
    "coughing": change_2_1_yes_no_to_1_0,
    "shortness_of_breath": change_2_1_yes_no_to_1_0,
    "swallowing_difficulty": change_2_1_yes_no_to_1_0,
    "chest_pain": change_2_1_yes_no_to_1_0
}, inplace=True)

,gender,age,smoking,yellow_fingers,anxiety,peer_pressure,chronic_disease,fatigue,allergy,wheezing,alcohol_consumption,coughing,shortness_of_breath,swallowing_difficulty,chest_pain,target
0,0,69,0,1,1,0,0,1,0,1,1,1,1,1,1,1
1,0,74,1,0,0,0,1,1,1,0,0,0,1,1,1,1
2,1,59,0,0,0,1,0,1,0,1,0,1,1,0,1,0
3,0,63,1,1,1,0,0,0,0,0,1,0,0,1,1,0
4,1,63,0,1,0,0,0,0,0,1,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,1,56,0,0,0,1,1,1,0,0,1,1,1,1,0,1
305,0,70,1,0,0,0,0,1,1,1,1,1,1,0,1,1
306,0,58,1,0,0,0,0,0,1,1,1,1,0,0,1,1
307,0,67,1,0,1,0,0,1,1,0,1,1,1,0,1,1
308,0,62,0,0,0,1,0,1,1,1,1,0,0,1,0,1

In [534]:
df = df.astype({"gender": "int64", "target": "int64"})
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   gender                 309 non-null    int64
 1   age                    309 non-null    int64
 2   smoking                309 non-null    int64
 3   yellow_fingers         309 non-null    int64
 4   anxiety                309 non-null    int64
 5   peer_pressure          309 non-null    int64
 6   chronic_disease        309 non-null    int64
 7   fatigue                309 non-null    int64
 8   allergy                309 non-null    int64
 9   wheezing               309 non-null    int64
 10  alcohol_consumption    309 non-null    int64
 11  coughing               309 non-null    int64
 12  shortness_of_breath    309 non-null    int64
 13  swallowing_difficulty  309 non-null    int64
 14  chest_pain             309 non-null    int64
 15  target                 309 non-null    int64
dtypes: int64(16)
memory usage: 38.8 KB

In [535]:
df['age'] = df['age'] / 100
df['target'].value_counts()

target
1    270
0     39
Name: count, dtype: int64

In [536]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [537]:
x = df.loc[:, df.columns != "target"]
y = df["target"]
x_test, x_train, y_test, y_train = train_test_split(x, y, stratify=y, test_size=0.2, random_state=2930)

In [538]:
pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("svc", SVC(kernel="poly", class_weight="balanced", random_state=2930, degree=3))
])
pipe.fit(x_train, y_train)
y_pred = pipe.predict(x_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.55      0.39      0.45        31
           1       0.92      0.95      0.93       216

    accuracy                           0.88       247
   macro avg       0.73      0.67      0.69       247
weighted avg       0.87      0.88      0.87       247

[[ 12  19]
 [ 10 206]]

In [539]:
grid = GridSearchCV(pipe, param_grid={
    'svc__C': [0.01, 0.1, 1, 10, 100],
    # 'svc__gamma': ['scale', 'auto', 0.01, 0.1, 1, 10],
    'svc__gamma': [1e-4, 1e-3, 1e-2, 1e-1, 1, "scale"]
}, cv=5, scoring="balanced_accuracy", n_jobs=-1)

grid.fit(x_train, y_train)
display(pd.DataFrame(grid.cv_results_).sort_values(by="mean_test_score", ascending=False))
print("Best parameters:", grid.best_params_)
best_model = grid.best_estimator_
y_pred = best_model.predict(x_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_svc__C,param_svc__gamma,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
15,0.001949,0.000482,0.001053,0.000291,1.00,0.1,"{'svc__C': 1, 'svc__gamma': 0.1}",0.5,1.00,0.5,0.5,1.00,0.70,0.244949,1
10,0.001976,0.000150,0.001016,0.000264,0.10,1,"{'svc__C': 0.1, 'svc__gamma': 1}",0.5,1.00,0.5,0.5,1.00,0.70,0.244949,1
28,0.001908,0.000156,0.000918,0.000146,100.00,1,"{'svc__C': 100, 'svc__gamma': 1}",0.5,1.00,0.5,0.5,1.00,0.70,0.244949,1
27,0.001897,0.000364,0.000815,0.000087,100.00,0.1,"{'svc__C': 100, 'svc__gamma': 0.1}",0.5,1.00,0.5,0.5,1.00,0.70,0.244949,1
23,0.001482,0.000146,0.000747,0.000051,10.00,scale,"{'svc__C': 10, 'svc__gamma': 'scale'}",0.5,1.00,0.5,0.5,1.00,0.70,0.244949,1
22,0.001770,0.000324,0.001249,0.000578,10.00,1,"{'svc__C': 10, 'svc__gamma': 1}",0.5,1.00,0.5,0.5,1.00,0.70,0.244949,1
21,0.002246,0.000768,0.001195,0.000795,10.00,0.1,"{'svc__C': 10, 'svc__gamma': 0.1}",0.5,1.00,0.5,0.5,1.00,0.70,0.244949,1
17,0.001897,0.000315,0.001233,0.000567,1.00,scale,"{'svc__C': 1, 'svc__gamma': 'scale'}",0.5,1.00,0.5,0.5,1.00,0.70,0.244949,1
16,0.001563,0.000199,0.000767,0.000043,1.00,1,"{'svc__C': 1, 'svc__gamma': 1}",0.5,1.00,0.5,0.5,1.00,0.70,0.244949,1
29,0.001827,0.000190,0.000829,0.000083,100.00,scale,"{'svc__C': 100, 'svc__gamma': 'scale'}",0.5,1.00,0.5,0.5,1.00,0.70,0.244949,1
4,0.002111,0.000351,0.000868,0.000066,0.01,1,"{'svc__C': 0.01, 'svc__gamma': 1}",0.5,1.00,0.5,0.5,1.00,0.70,0.244949,1
9,0.001528,0.000239,0.000745,0.000043,0.10,0.1,"{'svc__C': 0.1, 'svc__gamma': 0.1}",0.5,0.75,0.5,0.5,0.75,0.60,0.122474,12
26,0.001833,0.000255,0.001029,0.000312,100.00,0.01,"{'svc__C': 100, 'svc__gamma': 0.01}",0.5,0.75,0.5,0.5,0.75,0.60,0.122474,12
25,0.002118,0.000304,0.000904,0.000095,100.00,0.001,"{'svc__C': 100, 'svc__gamma': 0.001}",0.5,0.75,0.5,0.5,0.75,0.60,0.122474,12
24,0.002662,0.000610,0.001228,0.000469,100.00,0.0001,"{'svc__C': 100, 'svc__gamma': 0.0001}",0.5,0.75,0.5,0.5,0.75,0.60,0.122474,12
11,0.001821,0.000413,0.000813,0.000059,0.10,scale,"{'svc__C': 0.1, 'svc__gamma': 'scale'}",0.5,0.75,0.5,0.5,0.70,0.59,0.111355,16
2,0.001671,0.000227,0.000820,0.000049,0.01,0.01,"{'svc__C': 0.01, 'svc__gamma': 0.01}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17
3,0.002245,0.000512,0.001020,0.000219,0.01,0.1,"{'svc__C': 0.01, 'svc__gamma': 0.1}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17
5,0.002600,0.000729,0.001058,0.000427,0.01,scale,"{'svc__C': 0.01, 'svc__gamma': 'scale'}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17
6,0.001753,0.000169,0.001064,0.000339,0.10,0.0001,"{'svc__C': 0.1, 'svc__gamma': 0.0001}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17
20,0.002370,0.000747,0.001436,0.000624,10.00,0.01,"{'svc__C': 10, 'svc__gamma': 0.01}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17
19,0.002026,0.000596,0.000893,0.000238,10.00,0.001,"{'svc__C': 10, 'svc__gamma': 0.001}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17
18,0.002134,0.000517,0.001062,0.000326,10.00,0.0001,"{'svc__C': 10, 'svc__gamma': 0.0001}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17
7,0.001991,0.000514,0.000827,0.000091,0.10,0.001,"{'svc__C': 0.1, 'svc__gamma': 0.001}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17
8,0.001992,0.000397,0.001175,0.000294,0.10,0.01,"{'svc__C': 0.1, 'svc__gamma': 0.01}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17
1,0.001747,0.000214,0.000783,0.000032,0.01,0.001,"{'svc__C': 0.01, 'svc__gamma': 0.001}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17
14,0.001832,0.000596,0.000817,0.000084,1.00,0.01,"{'svc__C': 1, 'svc__gamma': 0.01}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17
13,0.001795,0.000282,0.000882,0.000207,1.00,0.001,"{'svc__C': 1, 'svc__gamma': 0.001}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17
12,0.001906,0.000397,0.000881,0.000133,1.00,0.0001,"{'svc__C': 1, 'svc__gamma': 0.0001}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17
0,0.001658,0.000190,0.000774,0.000118,0.01,0.0001,"{'svc__C': 0.01, 'svc__gamma': 0.0001}",0.5,0.50,0.5,0.5,0.50,0.50,0.000000,17

Best parameters: {'svc__C': 0.01, 'svc__gamma': 1}
              precision    recall  f1-score   support

           0       0.58      0.35      0.44        31
           1       0.91      0.96      0.94       216

    accuracy                           0.89       247
   macro avg       0.75      0.66      0.69       247
weighted avg       0.87      0.89      0.87       247

[[ 11  20]
 [  8 208]]